### PR TITLE
500 L2 Swedish sentences 

### PR DESCRIPTION
**Pull request by harisont**

### CODE REVIEW

**Comment by savary** [comment]
THank you for your data.

**Comment by harisont** [comment]
Thanks for merging! My understanding is that we are supposed to sync Arborator with this repository, but if that's the case, don't we also need push rights? I don't seem to be able to import the data from here right now.

**Comment by dan-zeman** [comment]
> Thanks for merging! My understanding is that we are supposed to sync Arborator with this repository, but if that's the case, don't we also need push rights? I don't seem to be able to import the data from here right now.

@bguil?

**Comment by dan-zeman** [comment]
I would assume that if this is a treebank you intend to eventually publish as part of UD, you should have a repository on UD GitHub and synchronize Arborator with the dev branch there.

**Comment by harisont** [comment]
@dan-zeman yes, I want SweLL to become a treebank in the short-medium term, but I will probably __not__ use the files from this training school directly. 

But regarding the future UD repo:

- how do I become a member (?) of the UD GitHub organization to create one?
- at what stage should I do that? Does the treebank need be ready for the next release when I push it there?
- can it be a fork of my own existing repo (which is still private atp?)

We can also discuss these things "live" of course :)

**Comment by dan-zeman** [comment]
You become a member when I generate a GitHub invitation for you and you accept it :-)

The treebank repository also has to be created by me (but as a member you will have push access to the dev branch). We will have to discuss the name (must fit the naming conventions we have), e.g. UD_Swedish-LL.

Not sure about the fork. I think I did this in the past with one treebank but now it might clash with the scripts I use to start up a repo.

As for the "stage", I typically encourage people to do it as soon as possible, to see what the UD validator thinks about it and to have enough time to make it valid before the next release (for which the deadline is November 1).

> We can also discuss these things "live" of course :)

Sure :-)

**Comment by bguil** [comment]
I've uploaded data [here](https://github.com/UniDive/2024-UniDive-Chisinau-training-school/tree/main/Course-1-dependency-syntax/data) just for make it available to everyone.

You cannot synchronized with arborator grew from this place. Anyway github synchronisation is not required for this week activies.

**Pull request merged**
